# Number of days of inactivity before an issue becomes stale
daysUntilStale: 14
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 0
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - enhancement
# Label to use when marking an issue as stale
staleLabel: bot
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: false
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  此问题长时间无活动，已被自动关闭